/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GovernanceToken } from "./GovernanceToken";
export type { VoterRegistry } from "./VoterRegistry";
export type { VotingEngine } from "./VotingEngine";
