/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVoterRegistry,
  IVoterRegistryInterface,
} from "../../../contracts/interfaces/IVoterRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVoterRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IVoterRegistryInterface {
    return new Interface(_abi) as IVoterRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVoterRegistry {
    return new Contract(address, _abi, runner) as unknown as IVoterRegistry;
  }
}
